#!/usr/bin/env python3
"""
// MongoDB Command File
"""

from pymongo import MongoClient

def list_databases():
    """
    List all databases in MongoDB.
    """
    try:
        client = MongoClient()

        databases = client.list_database_names()

        # Print the list of databases
        for db in databases:
            print(db)

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    list_databases()
